spring:
  datasource:
    url: jdbc:mysql://39.107.246.239:9876/ubt_vehicle?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r.
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    druid:
      filter:
        config:
          enabled: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false

  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  data:
    mongodb:
      host: 39.107.246.239
      port: 9874
      database: ubt_vehicle
      username: ubt_vehicle
      password: 1q2w3e4r
      authentication-database: ubt_vehicle
  redis:
    host: 39.107.246.239
    port: 9875
  jpa:
    show-sql: false
  application:
    name: service-vehicle

  iov2:
    activemq:
      in-memory: true
      broker-url: tcp://39.107.246.239:9527
      pool:
        enabled: false
        max-connections: 5
      user: admin
      password: admin
      packages:
        trust-all: true
  iov3:
    activemq:
      in-memory: true
      broker-url: tcp://39.107.246.239:9527
      pool:
        enabled: false
        max-connections: 5
      user: admin
      password: admin
      packages:
        trust-all: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
server:
  context-path: /vehicle-api
eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://riverroad:ilikebus@register-dev.riverroad.cn/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: 39.106.62.17
swagger:
  enabled: true
  title: ubt-vehicle
  description: vehicle 服务提供的调用接口~
  version: 1.0
  contact:
    name: windy
    email: linxc@riverroad.cn
  base-package: io.ubt.vehicle.web

#访问路径
management:
  context-path: /monitor
  health:
    diskspace:
      enabled: false
    hystrix:
      enabled: false
    refresh:
      enabled: false
# 禁用全部监控信息接口，只开放 health 接口
health:
  config:
    enabled: false
endpoints:
  enabled: false
  health:
    enabled: true

#### MQ 队列名 ####
jms:
  topic:
    destination:
      vehicleStatus: vehicle-status-topic
  virtualTopic:
    destination:
      vehicleTaskResult: VirtualTopic.vehicle-task-result
      vehicleEvent: VirtualTopic.vehicle-event
      deviceOnlineEvent: Consumer.service-vehicle.VirtualTopic.device-online
      deviceTaskResult: Consumer.service-vehicle.VirtualTopic.device-task-result
      mediaTaskResult: Consumer.service-vehicle.VirtualTopic.vehicle-library-media-sync
      deviceInitResult:  Consumer.service-vehicle.VirtualTopic.vehicle-media-info
      duoConfigInfo: Consumer.service-vehicle.VirtualTopic.device-duo-config-info
      safetyConfigInfo: Consumer.service-vehicle.VirtualTopic.device-safety-config-info
redis:
  key:
    ubt:
      vehicle:
        hash: ubt-vehicle-hash #最新 vehicle 集合key
      device:
        hash: ubt-router-hash #最新 device 集合key

#设备注册通知设备层接口地址（未使用feign的服务）
device:
  register:
    url:
      NetBoxSafety: http://39.106.62.17/tvbox_data/safety/dataservice/device/registers
      NetBoxDuo: http://39.106.62.17/nbd_support/router/create

settings:
  default-user-id: 1
  inhand:
    default-manuId: 1
  ubt-cloud:
    default-batch-id:
      net-box: 100001
      net-box-duo: 100002
      gps-sensor: 100003
      safety: 100004
  company-default:
    ssid:
      length: 100
      format: "[\"{companyName}\",\"{BusID}\"]"
# wifi配置速度对应翻译
wifi:
  speed:
    normal: "{\"time_limited\":{\"user_default_upload_speed\":1000,\"user_default_download_speed\":1000, \"vip_time\": 900000, \"user_default_limited_download_speed\": 10000, \"user_default_limited_upload_speed\": 1000},\"current_qos\":\"time_limited\"}"
    high: "{\"time_limited\":{\"user_default_upload_speed\":1000,\"user_default_download_speed\":5000, \"vip_time\": 900000, \"user_default_limited_download_speed\": 10000, \"user_default_limited_upload_speed\": 1000},\"current_qos\":\"time_limited\"}"
    time: "{\"defaultUploadSpeed\":1000, \"limitedUploadSpeed\": 1000,\"normal\":1000,\"high\":5000}"
    traffic: "{\"defaultUploadSpeed\":1000, \"limitedUploadSpeed\": 1000,\"normal\":1000,\"high\":5000}"
    dyna: 1000
    oneNormal:  "{\"defaultDownSpeed\":10,\"freeWifi\":\"Normal\",\"rateLimitTime\":15,\"type\":2}"
    oneHigh:  "{\"defaultDownSpeed\":10,\"freeWifi\":\"High\",\"rateLimitTime\":15,\"type\":2}"

# 通知设tracker备时区变更 URl地址
tracker:
  timezone:
    url: http://39.105.13.66/device-dal/timezones

